# SPDX-License-Identifier: Apache-2.0
"""End-to-end replay of real Claude Code traces through vLLM, with full
per-request instrumentation and an "anchor probe" between sessions.

Validates two HiMA claims simultaneously:

  L1 (anchor eviction under LRU): after every session ends, we issue a
      single small "anchor probe" — a prompt consisting of only the
      shared system-prompt prefix that is common to every cc session.
      We read `num_cached_tokens` from the probe to see how much of the
      anchor is still cached. Under LRU, as the cumulative new content
      from later sessions fills the KV pool, the anchor's blocks
      eventually fall off the tail of the free queue and get evicted —
      even though they have been hit by every preceding session.

  L2 (partial-block waste / bubble): every turn of every session is
      issued as a fresh request; we record (prompt_len,
      num_cached_tokens, partial_block_waste = prompt_len -
      num_cached_tokens - new_tokens_added_this_turn). We then plot the
      bubble accumulating turn-by-turn across the replayed workload.

All metrics are persisted to ``dev/e2e_replay.jsonl`` (one JSON per row,
one row per request, in chronological order). Plots are generated by
``dev/plot_results.py``.

Run via:
  cd /data/yuzhou/projects/vllm-songyang
  .venv/bin/python dev/e2e_replay.py | tee dev/e2e_replay.out
"""

from __future__ import annotations

import gc
import json
import os
import sys
import time
from pathlib import Path

# Workers spawn with a clean PATH; expose the venv's `ninja`.
_VENV_BIN = os.path.dirname(sys.executable)
if _VENV_BIN not in os.environ.get("PATH", ""):
    os.environ["PATH"] = f"{_VENV_BIN}:{os.environ.get('PATH', '')}"
os.environ.setdefault("VLLM_LOGGING_LEVEL", "INFO")

import torch
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams

MODEL = "Qwen/Qwen3.5-35B-A3B"
DATA = Path("/data/yuzhou/projects/sglang/dev/eval/datasets/cc_long_traces.jsonl")
BLOCK_SIZE = 1056

# Replay subset of sessions to keep runtime tractable (~30-90 min).
N_SESSIONS = 30
# Cap per-turn prompt length so we don't blow max_model_len.
MAX_PROMPT_TOKENS = 60_000

OUT_JSONL = Path("dev/e2e_replay.jsonl")
OUT_LOG = Path("dev/e2e_replay.out")


# --------------------- helpers --------------------- #

def flatten_content(content) -> str:
    if content is None:
        return ""
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return str(content)
    parts: list[str] = []
    for p in content:
        if isinstance(p, dict):
            t = p.get("type", "")
            if t == "text":
                parts.append(p.get("text", ""))
            elif t == "tool_use":
                inner = p.get("input", "")
                if not isinstance(inner, str):
                    inner = json.dumps(inner, ensure_ascii=False)
                parts.append(
                    f"<tool_use name={p.get('name', '')} "
                    f"id={p.get('id', '')}>{inner}</tool_use>"
                )
            elif t == "tool_result":
                inner = p.get("content", "")
                if isinstance(inner, list):
                    inner = "\n".join(
                        x.get("text", str(x)) if isinstance(x, dict) else str(x)
                        for x in inner
                    )
                elif not isinstance(inner, str):
                    inner = str(inner)
                parts.append(
                    f"<tool_result id={p.get('tool_use_id', '')}>"
                    f"{inner}</tool_result>"
                )
            else:
                parts.append(json.dumps(p, ensure_ascii=False))
        else:
            parts.append(str(p))
    return "\n".join(parts)


def msg_to_chunk(m: dict) -> str:
    role = m.get("role", "user")
    return f"<|im_start|>{role}\n{flatten_content(m.get('content'))}<|im_end|>\n"


def find_common_token_prefix(token_seqs: list[list[int]]) -> list[int]:
    if not token_seqs:
        return []
    min_len = min(len(s) for s in token_seqs)
    common_len = 0
    for i in range(min_len):
        tok = token_seqs[0][i]
        if all(s[i] == tok for s in token_seqs):
            common_len += 1
        else:
            break
    return token_seqs[0][:common_len]


# --------------------- main --------------------- #

def main() -> None:
    tokenizer = AutoTokenizer.from_pretrained(MODEL, trust_remote_code=True)

    print(f"Loading sessions from {DATA.name}...")
    sessions: list[list[dict]] = []
    with DATA.open() as f:
        for line in f:
            sessions.append(json.loads(line)["messages"])
    print(f"  {len(sessions)} total; using first {N_SESSIONS}")

    # ------------------ build anchor ------------------ #
    # Real cc sessions don't share a long token prefix (their tasks differ),
    # so we synthesize a clean anchor by taking session 0's first user
    # message (the system+task prompt — a few thousand tokens). We then
    # *warm it* with multiple hits to simulate the "shared anchor that
    # has been hit many times before the cold burst" pattern that HiMA L1
    # is concerned with. Cold burst = subsequent sessions' workload.
    first_user = next((m for m in sessions[0] if m["role"] == "user"), None)
    assert first_user is not None
    anchor_ids = tokenizer.encode(
        msg_to_chunk(first_user), add_special_tokens=False
    )
    anchor_len = len(anchor_ids)
    print(f"Anchor: session-0's first user message ({anchor_len} tokens)")
    print(f"  preview: {tokenizer.decode(anchor_ids[:60])!r}...")
    N_ANCHOR_WARM_HITS = 5  # simulate "shared anchor hit many times"

    # ------------------ spin up vLLM ------------------ #
    # Use util=0.45 to give a modest KV budget (~1-1.5M tokens),
    # so cumulative cc workload (~10M tokens of context) will force eviction.
    print(f"Loading {MODEL} (TP=2, mamba_cache_mode=align, "
          f"max_model_len={MAX_PROMPT_TOKENS + 1024}, util=0.45)...")
    llm = LLM(
        model=MODEL,
        tensor_parallel_size=2,
        dtype="bfloat16",
        enable_prefix_caching=True,
        mamba_cache_mode="align",
        max_model_len=MAX_PROMPT_TOKENS + 1024,
        gpu_memory_utilization=0.35,
        # Default max_num_seqs=1024 demands too many mamba slots at low util;
        # we only ever issue 1 request at a time, so 64 is plenty.
        max_num_seqs=64,
        trust_remote_code=True,
    )
    sp = SamplingParams(max_tokens=1, temperature=0.0)

    def issue(token_ids: list[int]) -> tuple[int, float]:
        t0 = time.monotonic()
        outs = llm.generate(
            prompts=[token_ids], sampling_params=sp, use_tqdm=False,
        )
        wall = time.monotonic() - t0
        return outs[0].num_cached_tokens or 0, wall

    # ------------------ replay ------------------ #
    OUT_JSONL.unlink(missing_ok=True)
    fout = OUT_JSONL.open("w")

    global_req_idx = 0
    cum_partial_block_waste = 0
    cum_new_content = 0
    t_start = time.monotonic()

    # Phase A: warm anchor — repeat issuance to give it many "hits" in the
    # eviction priority queue. After each hit, the anchor's blocks are
    # released back to the *tail* of the free queue.
    print(f"\nPhase A: warming anchor with {N_ANCHOR_WARM_HITS} hits...")
    for i in range(N_ANCHOR_WARM_HITS):
        cached, wall = issue(anchor_ids)
        row = {
            "kind": "anchor_warm",
            "global_idx": global_req_idx,
            "warm_iter": i,
            "prompt_len": anchor_len,
            "num_cached_tokens": cached,
            "wall_s": wall,
            "elapsed_s": time.monotonic() - t_start,
        }
        fout.write(json.dumps(row) + "\n")
        fout.flush()
        global_req_idx += 1
        print(f"  warm[{i}] cached={cached}/{anchor_len}")

    # Baseline anchor probe: should hit at full anchor_len (minus the
    # last partial block, which never gets cached — so floor//1056 × 1056).
    cached, wall = issue(anchor_ids)
    expected_anchor_cached = (anchor_len // BLOCK_SIZE) * BLOCK_SIZE
    print(f"\nBaseline anchor probe (post-warm): cached={cached} "
          f"(expected ~{expected_anchor_cached})")
    fout.write(json.dumps({
        "kind": "anchor_probe", "global_idx": global_req_idx,
        "after_session_idx": -1, "prompt_len": anchor_len,
        "num_cached_tokens": cached, "wall_s": wall,
        "elapsed_s": time.monotonic() - t_start,
    }) + "\n")
    fout.flush()
    global_req_idx += 1

    # Phase B: cold-burst workload = subsequent sessions, replayed in full.
    # After EACH session, probe anchor to see if its blocks survived.
    print(f"\nPhase B: replaying sessions 1..{N_SESSIONS - 1} with anchor "
          f"probes between sessions.\n")
    for s_idx in range(1, min(N_SESSIONS, len(sessions))):
        msgs = sessions[s_idx]

        # Build per-turn cumulative token sequences by appending each
        # message's token IDs (no full-string re-tokenization — O(N) total).
        running_ids: list[int] = []
        prev_len = 0
        turn_idx = 0

        for m_idx, m in enumerate(msgs):
            chunk = msg_to_chunk(m)
            piece_ids = tokenizer.encode(chunk, add_special_tokens=False)
            running_ids.extend(piece_ids)

            if m.get("role") != "assistant":
                continue
            if len(running_ids) > MAX_PROMPT_TOKENS:
                print(f"  [session {s_idx} turn {turn_idx}] "
                      f"prompt_len={len(running_ids)} > cap; truncating session")
                break

            ids = running_ids  # alias for clarity
            prompt_len = len(ids)
            cached, wall = issue(ids)
            partial_block_waste = (
                prev_len - cached if prev_len > 0 else 0
            )
            new_content = prompt_len - prev_len
            anchor_cached_tokens = min(cached, anchor_len)
            row = {
                "kind": "session_turn",
                "global_idx": global_req_idx,
                "session_idx": s_idx,
                "turn_idx": turn_idx,
                "prompt_len": prompt_len,
                "num_cached_tokens": cached,
                "partial_block_waste": max(partial_block_waste, 0),
                "new_content_tokens": new_content,
                "anchor_cached_tokens": anchor_cached_tokens,
                "anchor_fully_cached": int(cached >= anchor_len),
                "wall_s": wall,
                "elapsed_s": time.monotonic() - t_start,
            }
            fout.write(json.dumps(row) + "\n")
            fout.flush()
            if prev_len > 0:
                cum_partial_block_waste += max(partial_block_waste, 0)
                cum_new_content += new_content

            if global_req_idx % 10 == 0 or turn_idx == 0:
                pct = (
                    100.0 * cum_partial_block_waste / cum_new_content
                    if cum_new_content > 0
                    else 0.0
                )
                print(
                    f"  [g={global_req_idx:>4} s={s_idx:>3} t={turn_idx:>3}] "
                    f"plen={prompt_len:>6}  cached={cached:>6}  "
                    f"anchor={anchor_cached_tokens:>5}/{anchor_len}  "
                    f"cum_waste_pct={pct:.1f}%"
                )

            global_req_idx += 1
            prev_len = prompt_len
            turn_idx += 1

        # ------------- anchor probe between sessions ------------- #
        # Issue the bare anchor prompt and see how many tokens are
        # still cached — directly answers the L1 anchor eviction question.
        if anchor_len > 0:
            cached, wall = issue(anchor_ids)
            row = {
                "kind": "anchor_probe",
                "global_idx": global_req_idx,
                "after_session_idx": s_idx,
                "prompt_len": anchor_len,
                "num_cached_tokens": cached,
                "anchor_fully_cached": int(cached >= anchor_len - BLOCK_SIZE),
                "wall_s": wall,
                "elapsed_s": time.monotonic() - t_start,
            }
            fout.write(json.dumps(row) + "\n")
            fout.flush()
            global_req_idx += 1
            survival_pct = 100.0 * cached / anchor_len
            print(
                f"  [anchor probe after session {s_idx:>3}] "
                f"anchor_cached={cached}/{anchor_len} "
                f"({survival_pct:.1f}% survives)"
            )

    fout.close()
    print(
        f"\nDone. {global_req_idx} requests issued in "
        f"{time.monotonic() - t_start:.0f}s."
    )
    print(f"  cum_partial_block_waste = {cum_partial_block_waste:,} tokens")
    print(f"  cum_new_content         = {cum_new_content:,} tokens")
    if cum_new_content:
        print(
            f"  workload-weighted waste = "
            f"{100 * cum_partial_block_waste / cum_new_content:.2f}%"
        )
    print(f"\nLog written to {OUT_JSONL}")


if __name__ == "__main__":
    try:
        main()
    finally:
        torch.cuda.empty_cache()
        gc.collect()
